[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/pages/*"
  to = "/.netlify/functions/servePage"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[template.environment]
  ADMIN_SECRET = "Change this to a secure secret"
  NETLIFY_BLOB_STORE = "Your Netlify Blob Store name"