import React from 'react';
import { Plus, Minus } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

export function FAQ() {
  const [openIndex, setOpenIndex] = React.useState<number | null>(null);

  const faqs = [
    {
      question: "How does it work?",
      answer: "Mia Agency provides an automated AI-driven solution to streamline and enhance digital marketing. Mia, the core of this platform, generates SEO-optimized blog articles designed to drive traffic to your website. Operating 24/7, Mia consistently creates and uploads relevant content, helping businesses maintain a steady online presence and attract organic visitors without needing extensive manual effort."
    },
    {
      question: "Why does it work?",
      answer: "Mia's approach is built on continuous content generation, targeting, and reinforcement learning. By regularly analyzing audience engagement and adjusting its strategies, Mia improves over time. The AI generates a consistent stream of relevant, engaging content that answers your audience's questions, builds trust, and increases conversions. This method reduces dependency on costly, short-lived advertising campaigns, providing a sustainable path to long-term growth."
    },
    {
      question: "Is the content unique?",
      answer: "Yes, all content generated by Mia is unique and customized for each business. Mia gathers data specific to your industry and uses this information to create articles that are both relevant and valuable. Each piece is optimized with strategically chosen keywords to boost SEO, helping your content stand out in search results."
    },
    {
      question: "Is it good for Google rankings?",
      answer: "Absolutely. Mia's automated content is specifically designed to improve SEO. By consistently producing updated, optimized content, Mia enhances your website's visibility on search engines. This consistency is essential for ranking well on Google, as fresh and relevant content signals to search engines that your site provides valuable information for users."
    },
    {
      question: "How does Mia learn?",
      answer: "Mia learns through reinforcement learning—a method where the AI evaluates past performance and adjusts future content based on what resonates best with the audience. By analyzing interactions, engagement levels, and conversions, Mia refines its approach to continually improve results. This learning process enables it to effectively target high-converting audiences, enhancing its accuracy and impact over time."
    }
  ];

  return (
    <section className="py-20 bg-dark-purple/30">
      <div className="container mx-auto px-6">
        <h2 className="text-3xl font-bold text-center mb-12 text-white">Frequently Asked Questions</h2>
        <div className="max-w-3xl mx-auto space-y-4">
          {faqs.map((faq, index) => (
            <div
              key={index}
              className="bg-dark-purple/50 backdrop-blur-sm border border-white/5 rounded-xl overflow-hidden"
            >
              <button
                onClick={() => setOpenIndex(openIndex === index ? null : index)}
                className="w-full text-left px-6 py-4 flex items-center justify-between hover:bg-white/5 transition-colors"
              >
                <span className="text-lg font-medium text-white">{faq.question}</span>
                {openIndex === index ? (
                  <Minus className="h-5 w-5 text-pink-500 flex-shrink-0" />
                ) : (
                  <Plus className="h-5 w-5 text-pink-500 flex-shrink-0" />
                )}
              </button>
              <AnimatePresence>
                {openIndex === index && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.3 }}
                  >
                    <div className="px-6 pb-4">
                      <p className="text-white/70">{faq.answer}</p>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}